[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor           = "#3d7fc1"
backgroundColor        = "#0f1e31"
secondaryBackgroundColor = "#162847"
textColor              = "#e8edf2"
font                   = "sans serif"

[client]
showErrorDetails = "none"

[browser]
gatherUsageStats = false
serverAddress = "climebot.dsl.unibe.ch"
serverPort = 443
